### ISSUE TITLE
Production build fails at gulp-uncss

### ISSUE THREAD

**Issue by jem-Solytica** [zurb/foundation-ssg#8]
**Issue:**
Production build fails on a clean download/install (from "https://github.com/zurb/foundation-ssg/archive/master.zip"), when running
```
$ gulp build --production
```

**Workaround:**
Comment the `.pipe(uncss)` line in the 'sass' task of gulpfile.js.

**Log:**
```
$ gulp build --production
[22:12:35] Using gulpfile ~/f6test1/gulpfile.js
[22:12:35] Starting 'build'...
[22:12:35] Starting 'clean'...
[22:12:35] Finished 'clean' after 26 ms
[22:12:35] Starting 'pages'...
[22:12:35] Finished 'pages' after 42 ms
[22:12:35] Starting 'sass'...
[22:12:37] Starting 'javascript'...
[22:12:37] Starting 'images'...
[22:12:38] gulp-imagemin: Minified 0 images
[22:12:38] Finished 'images' after 840 ms
[22:12:45] Finished 'javascript' after 8.76 s

/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
Error: uncss/node_modules/css: unable to parse undefined:
property missing ':' near line 1:24346
	1:     -> ground-image:url("data:image/png;base64,
	2:        

    at error (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:57:15)
    at declaration (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:189:33)
    at declarations (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:219:19)
    at rule (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:481:21)
    at rules (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:103:56)
    at stylesheet (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:73:16)
    at Object.module.exports [as parse] (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:485:10)
    at process (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:158:22)
    at tryCatcher (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:501:31)
    at Promise._settlePromiseAt (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/jem/f6test1/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Node Modules:**
```
$ npm ls --depth=0
foundation-ssg@0.0.1 /home/jem/f6test1
├── foundation-sites@6.0.0-alpha.2
├── gulp@3.9.0
├── gulp-autoprefixer@2.3.1
├── gulp-concat@2.6.0
├── gulp-extname@0.2.0
├── gulp-if@1.2.5
├── gulp-imagemin@2.4.0
├── gulp-load-plugins@0.10.0
├── gulp-sass@2.1.0
├── gulp-uglify@1.4.2
├── gulp-uncss@1.0.4
├── gulp-webserver@0.9.1
├── jquery@2.1.4
├── panini@0.1.0
├── rimraf@2.4.3
├── run-sequence@1.1.4
└── yargs@3.29.0
```

**gulp version:**
```
$ gulp --version
[22:15:14] CLI version 3.9.0
[22:15:14] Local version 3.9.0
```

**Linux version:**
```
[Ubuntu 15.04, Virtual Machine via Windows 10 Hyper-V]
$ uname -a
Linux webdev 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86
_64 x86_64 GNU/Linux
```

**Comment by gakimball** [comment]
Just made a bunch of refinements to the Gulpfile, everything appears to be working fine now.
